name: Deploy PR Preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    # github actions environment variables
    environment:
      name: pr-${{ github.event.pull_request.number }}
      url: https://pr-${{ github.event.pull_request.number }}.staging.gettravelvisa.com

    steps:
      - uses: actions/checkout@v5

      - name: Prepare Deployment Name
        run: |
          sed -i "s/__WORKER_ENVIRONMENT__/pr-${{ github.event.pull_request.number }}/g" wrangler.jsonc

      - name: ðŸ¤Œ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:open-next
        env:
          NEXT_PUBLIC_GTM_ID: ${{ vars.NEXT_PUBLIC_GTM_ID }}

      - name: Apply D1 Migrations
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          environment: staging
          wranglerVersion: "4.33.1"
          command: d1 migrations apply gtv-db-staging

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          environment: pr-${{ github.event.pull_request.number }}
          wranglerVersion: "4.33.1"
          vars: |
            NEXT_PUBLIC_GTM_ID
        env:
          NEXT_PUBLIC_GTM_ID: ${{ vars.NEXT_PUBLIC_GTM_ID }}
